services:
  backend:
    build:
      context: .
      target: builder
    command: sh -c "go install github.com/air-verse/air@latest && air"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - .env

  database:
    image: postgres:18
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
  app:
