package routes

import (
	_ "github.com/dev-xero/chess.io/docs" // auto-generated by Swag
	"github.com/dev-xero/chess.io/internal/config"
	"github.com/dev-xero/chess.io/internal/handlers"
	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/adaptor"
	httpSwagger "github.com/swaggo/http-swagger/v2"
	"gorm.io/gorm"
)

// @title Chess.io Swagger Specification
// @version 1.0
// @description This is the swagger specification for chess.io

// @contact.name API Support
// @contact.url http://github.com/dev-xero

// @license.name MIT
// @license.url https://mit-license.org

// @BasePath /v1
func Bootstrap(app *fiber.App, db *gorm.DB, cfg *config.Config) {
	rootHandler := &handlers.RootHandler{}

	api := app.Group("/api/v1")
	api.Get("/", rootHandler.Get)
	api.Get("/schema/swagger/*", adaptor.HTTPHandler(httpSwagger.Handler()))
}
