definitions:
  models.Player:
    properties:
      bio:
        type: string
      created_at:
        type: string
      elo_rating:
        type: integer
      player_id:
        type: string
      secret_question:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: endpoints for interacting with the backend
  title: chess.io specification
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Handle requests to the base endpoint
      tags:
      - base
  /api/v1/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Handle requests to the api root endpoint
      tags:
      - root
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Player'
      summary: Handles player registration requests
      tags:
      - authentication
  /health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Handle requests to the health check endpoint
      tags:
      - base
swagger: "2.0"
